// <auto-generated />
// このファイルはEntity Framework Coreによって自動生成されます
// 手動で編集しないでください
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SUSWebApp.Server.Data;

#nullable disable

namespace SUSWebApp.Server.Migrations
{
    /// <summary>
    /// 現在のデータベースモデルのスナップショット
    /// マイグレーション時点のモデル構造を保存
    /// </summary>
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        /// <summary>
        /// モデル構築メソッド
        /// Entity Frameworkが使用するモデル定義
        /// </summary>
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618  // 廃止予定の警告を抑制

            // PostgreSQL 9.0.8、識別子最大長63文字
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            // PostgreSQL用のID自動生成設定
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ===== AUTH_USER エンティティ定義 =====
            modelBuilder.Entity("SUSWebApp.Server.Models.Entities.AuthUser", b =>
            {
                b.Property<string>("EmployeeNo")
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("employee_no");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("password");

                b.HasKey("EmployeeNo");

                b.ToTable("AUTH_USER", (string)null);
            });

            // ===== DeviceHistory エンティティ定義（簡易版） =====
            modelBuilder.Entity("SUSWebApp.Server.Models.Entities.DeviceHistory", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ChangeContent")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("ChangeDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ChangeField")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("TargetAssetNo")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("UpdaterEmployeeNo")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("DeviceHistories");
            });

            // ===== HST_DEVICE_CHANGE エンティティ定義 =====
            modelBuilder.Entity("SUSWebApp.Server.Models.Entities.HstDeviceChange", b =>
            {
                b.Property<int>("ChangeId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("change_id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChangeId"));

                b.Property<string>("AssetNo")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("character varying(20)")
                    .HasColumnName("asset_no");

                // 他のプロパティ定義...（省略）

                b.HasKey("ChangeId");

                b.ToTable("HST_DEVICE_CHANGE", (string)null);
            });

            // ===== HST_USER_CHANGE エンティティ定義 =====
            modelBuilder.Entity("SUSWebApp.Server.Models.Entities.HstUserChange", b =>
            {
                // プロパティ定義...（省略）
                b.HasKey("ChangeId");
                b.ToTable("HST_USER_CHANGE", (string)null);
            });

            // ===== MST_DEVICE エンティティ定義 =====
            modelBuilder.Entity("SUSWebApp.Server.Models.Entities.MstDevice", b =>
            {
                // プロパティ定義...（省略）
                b.HasKey("AssetNo");
                b.ToTable("MST_DEVICE", (string)null);
            });

            // ===== MST_USER エンティティ定義 =====
            modelBuilder.Entity("SUSWebApp.Server.Models.Entities.MstUser", b =>
            {
                // プロパティ定義...（省略）
                b.HasKey("EmployeeNo");
                b.ToTable("MST_USER", (string)null);
            });

            // ===== TRN_RENTAL エンティティ定義 =====
            modelBuilder.Entity("SUSWebApp.Server.Models.Entities.TrnRental", b =>
            {
                // プロパティ定義...（省略）
                b.HasKey("RentalId");

                // インデックス定義
                b.HasIndex("AssetNo")
                    .HasDatabaseName("IX_TRN_RENTAL_ASSET_NO");

                b.ToTable("TRN_RENTAL", (string)null);
            });

#pragma warning restore 612, 618
        }
    }
}